// books.js — registry of all live books and chapter counts
// Auto-generated by rebuild_books_js() in shared.py — do not edit manually
var BOOKS = [
  {dir:"genesis",name:"Genesis",total:50,live:50,testament:"OT"},
  {dir:"exodus",name:"Exodus",total:40,live:40,testament:"OT"},
  {dir:"leviticus",name:"Leviticus",total:27,live:27,testament:"OT"},
  {dir:"numbers",name:"Numbers",total:36,live:6,testament:"OT"},
  {dir:"ruth",name:"Ruth",total:4,live:4,testament:"OT"},
  {dir:"proverbs",name:"Proverbs",total:31,live:31,testament:"OT"},
  {dir:"matthew",name:"Matthew",total:28,live:28,testament:"NT"},
  {dir:"mark",name:"Mark",total:16,live:16,testament:"NT"},
  {dir:"luke",name:"Luke",total:24,live:24,testament:"NT"},
  {dir:"john",name:"John",total:21,live:21,testament:"NT"},
  {dir:"acts",name:"Acts",total:28,live:28,testament:"NT"}
];
