// books.js — registry of all live books and chapter counts
// Auto-generated by rebuild_books_js() in shared.py — do not edit manually
var BOOKS = [
  {dir:"genesis",name:"Genesis",total:50,live:50,testament:"OT"},
  {dir:"exodus",name:"Exodus",total:40,live:40,testament:"OT"},
  {dir:"leviticus",name:"Leviticus",total:27,live:27,testament:"OT"},
  {dir:"numbers",name:"Numbers",total:36,live:36,testament:"OT"},
  {dir:"deuteronomy",name:"Deuteronomy",total:34,live:34,testament:"OT"},
  {dir:"joshua",name:"Joshua",total:24,live:24,testament:"OT"},
  {dir:"judges",name:"Judges",total:21,live:21,testament:"OT"},
  {dir:"1_samuel",name:"1 Samuel",total:31,live:31,testament:"OT"},
  {dir:"2_samuel",name:"2 Samuel",total:24,live:24,testament:"OT"},
  {dir:"1_kings",name:"1 Kings",total:22,live:22,testament:"OT"},
  {dir:"2_kings",name:"2 Kings",total:25,live:25,testament:"OT"},
  {dir:"1_chronicles",name:"1 Chronicles",total:29,live:4,testament:"OT"},
  {dir:"ruth",name:"Ruth",total:4,live:4,testament:"OT"},
  {dir:"proverbs",name:"Proverbs",total:31,live:31,testament:"OT"},
  {dir:"matthew",name:"Matthew",total:28,live:28,testament:"NT"},
  {dir:"mark",name:"Mark",total:16,live:16,testament:"NT"},
  {dir:"luke",name:"Luke",total:24,live:24,testament:"NT"},
  {dir:"john",name:"John",total:21,live:21,testament:"NT"},
  {dir:"acts",name:"Acts",total:28,live:28,testament:"NT"}
];
