#!/usr/bin/env python3
"""review_queue.py — Produce GitHub issue drafts for flagged samples (#1468).

Does NOT call the GitHub API directly — it writes issue drafts to a
directory so humans (or a follow-up `gh issue create` invocation) can
review them before anything reaches the repo. This keeps the pipeline
safe against runaway issue creation if the classifier drifts.

Usage:
    python3 _tools/amicus_audit/review_queue.py \\
        --in cache/2026-06-01.classified.json \\
        --out cache/2026-06-01/issues/
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import Iterable, Optional


LABEL = 'amicus-audit'


def _safe_filename(title: str, sample_id: str) -> str:
    slug = re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')[:50]
    if not slug:
        slug = 'sample'
    return f'{slug}-{sample_id[:12]}.md'


def _short_summary(query: str, limit: int = 60) -> str:
    trimmed = (query or '').strip().replace('\n', ' ')
    if len(trimmed) <= limit:
        return trimmed or '(empty query)'
    cut = trimmed[:limit]
    if ' ' in cut[30:]:
        cut = cut[:cut.rfind(' ')]
    return f'{cut}…'


def issue_draft(sample: dict) -> dict:
    title = f'amicus-audit: {_short_summary(sample.get("query_text", ""))}'
    failing = sample.get('failing_check_ids') or []
    results = sample.get('classifier_results') or []
    chunks = sample.get('retrieved_chunks') or []

    body_lines: list[str] = []
    body_lines.append(f'**Sample id:** `{sample.get("sample_id")}`')
    body_lines.append(f'**Captured at:** {sample.get("captured_at")}')
    body_lines.append(f'**Reason:** `{sample.get("sample_reason")}`')
    body_lines.append(f'**Model tier:** `{sample.get("model_tier")}`')
    if sample.get('current_chapter_ref'):
        body_lines.append(f'**Chapter ref:** `{sample["current_chapter_ref"]}`')
    body_lines.append('')

    body_lines.append('## Query')
    body_lines.append('```')
    body_lines.append(sample.get('query_text') or '')
    body_lines.append('```')
    body_lines.append('')

    body_lines.append('## Compressed profile')
    body_lines.append('```')
    body_lines.append(sample.get('compressed_profile') or '(none)')
    body_lines.append('```')
    body_lines.append('')

    body_lines.append('## Response')
    body_lines.append('```')
    body_lines.append(sample.get('response_text') or '')
    body_lines.append('```')
    body_lines.append('')

    if chunks:
        body_lines.append('## Retrieved chunks')
        for c in chunks:
            cid = c.get('chunk_id') if isinstance(c, dict) else ''
            st = c.get('source_type') if isinstance(c, dict) else ''
            body_lines.append(f'- `{cid}` ({st})')
        body_lines.append('')

    if results:
        body_lines.append('## Classifier results')
        for r in results:
            icon = '✅' if r.get('passed') else '❌'
            detail = f' — {r["detail"]}' if r.get('detail') else ''
            body_lines.append(f'- {icon} `{r.get("check_id")}`{detail}')
        body_lines.append('')

    if failing:
        body_lines.append('## Failing checks')
        for cid in failing:
            body_lines.append(f'- `{cid}`')
        body_lines.append('')

    body_lines.append(
        '<!-- generated by _tools/amicus_audit/review_queue.py — do not edit by hand -->',
    )
    return {'title': title, 'body': '\n'.join(body_lines), 'labels': [LABEL]}


def should_escalate(sample: dict) -> bool:
    """Gap-signal / user-feedback samples always escalate; otherwise only
    samples the classifier flagged."""
    if sample.get('sample_reason') in ('gap_signal', 'user_feedback'):
        return True
    return bool(sample.get('failing_check_ids'))


def write_drafts(
    classified_samples: Iterable[dict],
    out_dir: str,
) -> int:
    os.makedirs(out_dir, exist_ok=True)
    written = 0
    for s in classified_samples:
        if not should_escalate(s):
            continue
        draft = issue_draft(s)
        path = os.path.join(
            out_dir,
            _safe_filename(draft['title'], s.get('sample_id') or ''),
        )
        with open(path, 'w', encoding='utf-8') as f:
            f.write(f'# {draft["title"]}\n\n')
            f.write(f'Labels: `{", ".join(draft["labels"])}`\n\n')
            f.write(draft['body'])
            f.write('\n')
        written += 1
    return written


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description='Emit GitHub issue drafts for flagged samples.')
    p.add_argument('--in', dest='in_path', required=True,
                   help='JSON file produced by classifier.py.')
    p.add_argument('--out', dest='out_dir', required=True,
                   help='Directory where Markdown issue drafts are written.')
    args = p.parse_args(argv)

    with open(args.in_path, 'r', encoding='utf-8') as f:
        samples = json.load(f)
    n = write_drafts(samples, args.out_dir)
    print(f'wrote {n} issue drafts to {args.out_dir}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
